### ISSUE TITLE
Named labels and heatmaps

### ISSUE THREAD

**Issue by FilippoPolo** [predictionmachines/FSharpIDD#13]
In the attached file, hovering the mouse over the heatmap shows the coordinate. Given that this chart has named ticks for its axes, however, I think it should show the corresponding tick names instead (or maybe there should be an option to specify what behavior to adopt).

![img](https://user-images.githubusercontent.com/9450467/50403825-221e0580-07a2-11e9-9e58-d7bfd52329f9.png)

**Comment by dgrechka** [comment]
Fixed in commit 6309fa3

![image](https://user-images.githubusercontent.com/5637547/50481012-51c24d00-09f0-11e9-841c-71344f75fe64.png)
